-- =====================================================================
-- generated_espn_team_mappings.sql  (auto-generated, DO NOT HAND-EDIT)
-- =====================================================================
--
-- Generated by scripts/bootstrap_espn_team_mappings.py
-- Provider: 'espn'
-- Canonical team source: seed
-- Total ESPN teams seen:        124
-- Successful mappings:          124
--   • abbreviation match:       113
--   • display-name fallback:    11
-- Abbreviation mismatches:      11
-- Unresolved ESPN teams:        0
-- Ambiguous matches:            0
--
-- This file performs an idempotent upsert into
-- public.provider_team_mappings using the natural key
-- (provider, provider_team_id). Re-running this file is safe.
--
-- Review carefully before applying. In particular, every row
-- flagged with 'abbreviation mismatch' in `notes` should be
-- spot-checked: the ESPN team was matched against a canonical
-- team whose abbreviation differs (e.g. ESPN 'WSH' → canonical
-- 'WAS'). The match itself is by display name, not abbreviation.
-- =====================================================================

INSERT INTO public.provider_team_mappings (
    provider,
    provider_team_id,
    team_id,
    notes
) VALUES
    ('espn', 'mlb:29', 'c97a2f68-2760-5e47-a5f3-4f3096b65a24', 'ESPN: Arizona Diamondbacks; abbr=ARI; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:11', '7b4666e2-e7cf-5092-aa1d-fab388657e57', 'ESPN: Athletics Athletics; abbr=ATH; matched via name_fallback; abbreviation mismatch (ESPN=ATH vs canonical=OAK); generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:15', '8d7e8dc1-d56c-5190-b9b8-06ee2d26505d', 'ESPN: Atlanta Braves; abbr=ATL; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:1', 'f062826c-46c9-58b8-8c14-33d37babfbe5', 'ESPN: Baltimore Orioles; abbr=BAL; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:2', '56520c93-515b-5317-b747-065d516ccdb4', 'ESPN: Boston Red Sox; abbr=BOS; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:16', '4b0df026-4d39-5c94-9315-0e98e68aab97', 'ESPN: Chicago Cubs; abbr=CHC; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:4', 'cd9be283-ee12-5983-a8d3-3afa1a3f8542', 'ESPN: Chicago White Sox; abbr=CHW; matched via name_fallback; abbreviation mismatch (ESPN=CHW vs canonical=CWS); generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:17', '491f448e-1730-526a-9590-126c89e6ab33', 'ESPN: Cincinnati Reds; abbr=CIN; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:5', '0094b51e-b6cf-571f-9356-387bbd452876', 'ESPN: Cleveland Guardians; abbr=CLE; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:27', 'c2512ae2-35d2-50a1-85bd-0e5550567792', 'ESPN: Colorado Rockies; abbr=COL; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:6', '689db5fe-4a79-5d3e-80ec-02a4cfd1727a', 'ESPN: Detroit Tigers; abbr=DET; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:18', '5acf8858-a701-5700-88af-e2bb20ba4fe4', 'ESPN: Houston Astros; abbr=HOU; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:7', '01d38a1c-11b2-5426-a585-565ca0596618', 'ESPN: Kansas City Royals; abbr=KC; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:3', 'c1c51594-d91c-5937-bf86-8271c0522dcf', 'ESPN: Los Angeles Angels; abbr=LAA; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:19', '1b5b3610-92f8-5466-a76b-114ad4a197ac', 'ESPN: Los Angeles Dodgers; abbr=LAD; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:28', '9ec438f9-db0c-5131-9131-1922106a7bce', 'ESPN: Miami Marlins; abbr=MIA; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:8', '50e524e1-36ef-5a10-9e67-8e0cafb07cf8', 'ESPN: Milwaukee Brewers; abbr=MIL; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:9', '50d4d600-c394-514b-ab1e-25ba53ebc572', 'ESPN: Minnesota Twins; abbr=MIN; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:21', 'f41b7f44-bbf1-5d8f-999d-9eec9454a78a', 'ESPN: New York Mets; abbr=NYM; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:10', '341e8ba8-6b2b-528a-b1f6-2230be44e1c2', 'ESPN: New York Yankees; abbr=NYY; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:22', '2464726d-81f6-5f3b-b61a-704bdcc36577', 'ESPN: Philadelphia Phillies; abbr=PHI; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:23', '175be0df-b239-514f-9256-6ed1b64106b9', 'ESPN: Pittsburgh Pirates; abbr=PIT; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:25', '6511cc9f-3c25-502a-a42f-a4bddcdc634e', 'ESPN: San Diego Padres; abbr=SD; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:12', '7c1126b7-b5b3-582c-b43b-24637eec88c7', 'ESPN: Seattle Mariners; abbr=SEA; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:26', '822bf54c-218f-51fd-a053-0c2440236b31', 'ESPN: San Francisco Giants; abbr=SF; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:24', 'a10cbb48-d64d-569c-bf2c-432eba66c20f', 'ESPN: St. Louis Cardinals; abbr=STL; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:30', '059724c9-442f-5585-93f5-523859d7636b', 'ESPN: Tampa Bay Rays; abbr=TB; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:13', '0f84c545-da0c-5ff0-bdcc-392034640655', 'ESPN: Texas Rangers; abbr=TEX; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:14', 'd7201f36-2e32-5ee2-a912-7f1aa8f7a0c8', 'ESPN: Toronto Blue Jays; abbr=TOR; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'mlb:20', '7589c2ef-250c-5457-8cbb-51a580831109', 'ESPN: Washington Nationals; abbr=WSH; matched via name_fallback; abbreviation mismatch (ESPN=WSH vs canonical=WAS); generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:1', 'ac76f74d-082d-55ec-bc9b-5907b2d55b0d', 'ESPN: Atlanta Hawks; abbr=ATL; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:17', '59612c15-88e3-502b-84cf-0c1c6d88d64a', 'ESPN: Brooklyn Nets; abbr=BKN; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:2', '87b616fa-f2a0-5466-a7ea-a6a5d36f51b8', 'ESPN: Boston Celtics; abbr=BOS; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:30', '2052480e-1e9b-5c16-a378-89c0c4a65f7f', 'ESPN: Charlotte Hornets; abbr=CHA; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:4', 'ac58ffa5-17b1-5386-a3cc-a9731b70b9fb', 'ESPN: Chicago Bulls; abbr=CHI; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:5', '96a5b630-fd8a-5eb9-bcff-ced95a171ecb', 'ESPN: Cleveland Cavaliers; abbr=CLE; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:6', 'aabac732-8086-51de-9c74-845761ee3bc2', 'ESPN: Dallas Mavericks; abbr=DAL; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:7', '1f912870-8efd-55d6-86db-df661344bb32', 'ESPN: Denver Nuggets; abbr=DEN; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:8', '553f7bc7-e256-57a5-8722-9968e7698461', 'ESPN: Detroit Pistons; abbr=DET; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:9', '874945b4-cf49-5905-b0c1-3696573117ca', 'ESPN: Golden State Warriors; abbr=GS; matched via name_fallback; abbreviation mismatch (ESPN=GS vs canonical=GSW); generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:10', '6eedbc66-313f-52f9-b29d-20ad47eda5d0', 'ESPN: Houston Rockets; abbr=HOU; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:11', '26d2427f-cf29-5499-8593-4ad74b1e2d2b', 'ESPN: Indiana Pacers; abbr=IND; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:12', 'e07e7287-5cd4-52cc-b6dd-a145863c0ac4', 'ESPN: LA Clippers; abbr=LAC; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:13', 'caa3a5d4-9bc7-5e6d-b922-4a040fa569dc', 'ESPN: Los Angeles Lakers; abbr=LAL; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:29', '3b566336-d116-5b50-92c4-be68e9413ff7', 'ESPN: Memphis Grizzlies; abbr=MEM; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:14', 'c33af5d9-1884-5261-a8ac-39dc5668aca3', 'ESPN: Miami Heat; abbr=MIA; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:15', '899af24b-0bd1-5b6c-9a72-94087aba78da', 'ESPN: Milwaukee Bucks; abbr=MIL; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:16', '987080cf-0edf-54f2-9e78-d6526ab43858', 'ESPN: Minnesota Timberwolves; abbr=MIN; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:3', '619ba0e4-db50-5214-bbe5-af1f08f3699f', 'ESPN: New Orleans Pelicans; abbr=NO; matched via name_fallback; abbreviation mismatch (ESPN=NO vs canonical=NOP); generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:18', '4c9cbfa5-a846-50ae-b43a-120ec02b6d45', 'ESPN: New York Knicks; abbr=NY; matched via name_fallback; abbreviation mismatch (ESPN=NY vs canonical=NYK); generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:25', '87a9013a-5fb0-5e12-97ae-8bd4aa41613a', 'ESPN: Oklahoma City Thunder; abbr=OKC; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:19', 'ddb4fd7f-8e75-50fc-b719-30be503ef9bb', 'ESPN: Orlando Magic; abbr=ORL; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:20', '5b0e5c30-9989-576c-ada6-2e4e84d2a3ca', 'ESPN: Philadelphia 76ers; abbr=PHI; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:21', '694fc072-d7da-568d-b7c6-acce2b1c2a4e', 'ESPN: Phoenix Suns; abbr=PHX; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:22', '58db9beb-20cf-5a7a-8eee-b1f6368b5005', 'ESPN: Portland Trail Blazers; abbr=POR; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:24', 'f58ed9a7-33e8-5af0-8595-51810345049d', 'ESPN: San Antonio Spurs; abbr=SA; matched via name_fallback; abbreviation mismatch (ESPN=SA vs canonical=SAS); generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:23', 'ae86d8d8-6cb0-5e5e-a1bd-45e7353bcd80', 'ESPN: Sacramento Kings; abbr=SAC; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:28', '9f297645-b0ef-50cc-abfe-7b65562f9782', 'ESPN: Toronto Raptors; abbr=TOR; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:26', '20c8b172-9b87-5fd6-9237-bfedfd8b6752', 'ESPN: Utah Jazz; abbr=UTAH; matched via name_fallback; abbreviation mismatch (ESPN=UTAH vs canonical=UTA); generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nba:27', '52654d39-6578-5da1-b09a-6a11086cff36', 'ESPN: Washington Wizards; abbr=WSH; matched via name_fallback; abbreviation mismatch (ESPN=WSH vs canonical=WAS); generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:22', '2bf4b498-d54e-5476-b2cc-db6bed9d63ac', 'ESPN: Arizona Cardinals; abbr=ARI; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:1', '9d5a4083-76b7-520d-bebf-105047a4a2d8', 'ESPN: Atlanta Falcons; abbr=ATL; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:33', '22780759-f816-5ee7-9559-65bbbbc21638', 'ESPN: Baltimore Ravens; abbr=BAL; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:2', '11994c05-dd06-594a-b2f7-e44200c48021', 'ESPN: Buffalo Bills; abbr=BUF; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:29', '04b20671-5f7b-5ee8-8b1d-02793fcc75c8', 'ESPN: Carolina Panthers; abbr=CAR; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:3', '88ce09dc-0da0-545e-ba29-aa82e71f654e', 'ESPN: Chicago Bears; abbr=CHI; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:4', '4bb02b9e-4ee2-57b0-bfae-eb5692126ffe', 'ESPN: Cincinnati Bengals; abbr=CIN; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:5', 'd37b36b3-dda2-5a59-ab14-b4efcf02753b', 'ESPN: Cleveland Browns; abbr=CLE; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:6', '250d2fad-d7ab-5733-bc88-92f18002094e', 'ESPN: Dallas Cowboys; abbr=DAL; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:7', 'fd15a67d-c95e-5e91-a838-548c809258db', 'ESPN: Denver Broncos; abbr=DEN; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:8', 'e9479cf9-7bd1-510f-bea3-b7101401e5c0', 'ESPN: Detroit Lions; abbr=DET; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:9', 'cd8b1e34-d36c-5103-a828-b52a055b6410', 'ESPN: Green Bay Packers; abbr=GB; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:34', 'd60de6a3-b7d1-5541-afda-eb4ee63eedc5', 'ESPN: Houston Texans; abbr=HOU; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:11', 'd0aaa486-6dd7-5965-b782-bbf133512dd5', 'ESPN: Indianapolis Colts; abbr=IND; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:30', '52493f6e-e20c-5f51-81df-2b3a2389f587', 'ESPN: Jacksonville Jaguars; abbr=JAX; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:12', 'c112d5cd-de2f-5deb-83c0-436709075975', 'ESPN: Kansas City Chiefs; abbr=KC; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:24', '6d11c9b4-8791-5b1c-9dc6-bf4d58f1dae5', 'ESPN: Los Angeles Chargers; abbr=LAC; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:14', 'ad4379c2-213a-50f8-af10-bdd229d0bc76', 'ESPN: Los Angeles Rams; abbr=LAR; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:13', '5db656d5-b847-5aba-b9c9-4123749b904d', 'ESPN: Las Vegas Raiders; abbr=LV; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:15', '932c5748-6f9e-58d1-bd73-d977c83353c0', 'ESPN: Miami Dolphins; abbr=MIA; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:16', '045f6330-ccae-501c-a709-2d09145e55f1', 'ESPN: Minnesota Vikings; abbr=MIN; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:17', '14e834e7-c90f-5833-8432-8f44540c370b', 'ESPN: New England Patriots; abbr=NE; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:18', 'bb957862-0feb-527a-8cf7-e5489b50b80b', 'ESPN: New Orleans Saints; abbr=NO; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:19', 'd1f84481-ce21-50c5-89a6-d1ae42347614', 'ESPN: New York Giants; abbr=NYG; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:20', '018dee72-6d20-53cb-bce6-5b505b3a9210', 'ESPN: New York Jets; abbr=NYJ; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:21', '21b63854-e92d-5364-9871-e0c65299083e', 'ESPN: Philadelphia Eagles; abbr=PHI; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:23', 'b4619367-b7a7-5af3-ad63-63ccff590e02', 'ESPN: Pittsburgh Steelers; abbr=PIT; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:26', '1ebc7038-200c-55d4-ab32-603156c6f50f', 'ESPN: Seattle Seahawks; abbr=SEA; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:25', 'e30be271-101d-53de-9100-b2fbd6edc251', 'ESPN: San Francisco 49ers; abbr=SF; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:27', '4933e099-5f2b-5c67-a7cb-ed36b2307c3f', 'ESPN: Tampa Bay Buccaneers; abbr=TB; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:10', '654615cb-5cfa-5923-b53e-97a76f43aac9', 'ESPN: Tennessee Titans; abbr=TEN; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nfl:28', 'bbe8fe9d-aa8b-51de-b24f-82bd530ac503', 'ESPN: Washington Commanders; abbr=WSH; matched via name_fallback; abbreviation mismatch (ESPN=WSH vs canonical=WAS); generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:25', 'e31df8ea-b24a-5cd1-a67b-659529a93b7b', 'ESPN: Anaheim Ducks; abbr=ANA; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:1', '398777ec-685a-5e2f-b63e-92384f404ab1', 'ESPN: Boston Bruins; abbr=BOS; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:2', 'e5f346f0-d43d-5f45-8226-ad3e38fe6433', 'ESPN: Buffalo Sabres; abbr=BUF; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:7', '826d349f-dfe2-5fd6-b85f-6be7e17a9bf0', 'ESPN: Carolina Hurricanes; abbr=CAR; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:29', 'e97a09b8-8f6a-56e3-a9e8-456b7130744c', 'ESPN: Columbus Blue Jackets; abbr=CBJ; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:3', '87642736-213c-5d7f-9d7f-21e5ebdecaac', 'ESPN: Calgary Flames; abbr=CGY; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:4', 'ccba440c-8ec0-5d71-8d6e-33880f4d0b33', 'ESPN: Chicago Blackhawks; abbr=CHI; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:17', '37ed5b13-55ee-5d02-9aea-763a98e16dfd', 'ESPN: Colorado Avalanche; abbr=COL; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:9', '480f810a-4312-54cc-9e1e-3980f39bb9c1', 'ESPN: Dallas Stars; abbr=DAL; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:5', '11b25e24-bb27-5310-8aa6-dfdf6de1193c', 'ESPN: Detroit Red Wings; abbr=DET; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:6', '010f541c-5778-5bf6-ab51-dc4de199bb37', 'ESPN: Edmonton Oilers; abbr=EDM; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:26', '76ca2040-b1f4-5322-8c92-9aa44a89e501', 'ESPN: Florida Panthers; abbr=FLA; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:8', '69f73db1-6711-51de-ad30-398421e5fe55', 'ESPN: Los Angeles Kings; abbr=LA; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:30', '146008c9-391f-5d64-9e49-2a38f6b28b89', 'ESPN: Minnesota Wild; abbr=MIN; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:10', 'd1ff3032-089e-535d-aef2-9ccafbc2af45', 'ESPN: Montreal Canadiens; abbr=MTL; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:11', '29fbad49-a4d8-5490-92df-a55ed3709ea8', 'ESPN: New Jersey Devils; abbr=NJ; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:27', 'e603989a-4727-5acf-8b04-efb201e0bd82', 'ESPN: Nashville Predators; abbr=NSH; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:12', 'd8acebdf-de7b-592d-9b34-7e5022908fb5', 'ESPN: New York Islanders; abbr=NYI; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:13', 'c31f8a46-07fa-5150-8e83-3880b11aa141', 'ESPN: New York Rangers; abbr=NYR; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:14', '089c1250-62ee-5abd-be78-4553ffff580e', 'ESPN: Ottawa Senators; abbr=OTT; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:15', '6b4acc2e-5706-5560-9710-25791ecbaae8', 'ESPN: Philadelphia Flyers; abbr=PHI; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:16', '14ed4dc4-c2b3-5c34-98ee-3a6c21c09959', 'ESPN: Pittsburgh Penguins; abbr=PIT; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:124292', '6f2c24ae-013b-5560-93c4-83548e3ee65b', 'ESPN: Seattle Kraken; abbr=SEA; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:18', '49fa35a1-a032-5e17-b76f-a55b53539c9a', 'ESPN: San Jose Sharks; abbr=SJ; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:19', '01c8b4c4-026d-55a4-a930-3956c5f7b342', 'ESPN: St. Louis Blues; abbr=STL; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:20', '8140ec6b-2c5b-59a0-a7da-824df368801c', 'ESPN: Tampa Bay Lightning; abbr=TB; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:21', 'de80c6fa-0da5-54db-aca1-c690a9bcb727', 'ESPN: Toronto Maple Leafs; abbr=TOR; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:129764', '378f0574-208a-5a9c-aa2c-7f5fc8bdd81d', 'ESPN: Utah Mammoth; abbr=UTAH; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:22', '4deca3fd-80f2-5679-aeb9-b9b45fbbe59c', 'ESPN: Vancouver Canucks; abbr=VAN; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:37', '87645952-ec79-5f88-82db-973af2d8cfa7', 'ESPN: Vegas Golden Knights; abbr=VGK; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:28', '59eeca27-b7f5-5adb-9e52-3cfb44075acc', 'ESPN: Winnipeg Jets; abbr=WPG; matched via abbreviation; generated by scripts/bootstrap_espn_team_mappings.py'),
    ('espn', 'nhl:23', '8d68c4f8-623a-582b-b8ef-d2bb6180ccfd', 'ESPN: Washington Capitals; abbr=WSH; matched via name_fallback; abbreviation mismatch (ESPN=WSH vs canonical=WAS); generated by scripts/bootstrap_espn_team_mappings.py')
ON CONFLICT (provider, provider_team_id) DO UPDATE SET
    team_id = EXCLUDED.team_id,
    notes   = EXCLUDED.notes;
